defaults:
  - base_config
  - path_config/juanubuntu
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

hydra:
  run:
    dir: ./outputs_hydra/${hydra.job.config_name}_${now:%Y%m%d}_${now:%H%M%S}
    # Other configs can be use here. For example:
    # dir: ./outputs_hydra/${hydra.job.config_name}_${global_device}

output_path: ${hydra:runtime.output_dir}
global_device: "cuda"

dataset_config:
  dataset_type: "measured-setpoint" # either "measured-setpoint" or "actual-measured"
  include_prev_measured: true

train_config:
  batch_size: 32
  epochs: 150
  lr: 0.0008
  log_interval: 1

actions:
  train: true
  test: true
  # show_images: true
  # save_test_predictions: true
  # calculate_metrics: false

test_config:
  batch_size: 32
# path_config:
#   workspace: ???
#   data_dir: ???
#   pretrained_weights_path: ???
#   training_output_path: ???
#   mapping_file: ???
#   weights_file: ???
#   predictions_path: ???

# train_config:
#   device: "${..global_device}"
#   epochs: 30
#   batch_size: 4
#   num_workers: 4
#   learning_rate: 1e-3
#   pretrained_weights_path: "${..path_config.pretrained_weights_path}"
#   training_output_path: "${..path_config.training_output_path}"

# test_config:
#   device: "${..global_device}"
#   batch_size: 1
#   num_workers: ${..train_config.num_workers}
#   weights_file: ${..path_config.trained_weights_file_path}/${..path_config.trained_weights_file_name}
#   predictions_dir: "${..path_config.predictions_path}"

