defaults:
  - base_config
  - path_config/juanubuntu_dataset5
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

hydra:
  run:
    dir: ./outputs_hydra/${hydra.job.config_name}_${now:%Y%m%d}_${now:%H%M%S}
    # Other configs can be use here. For example:
    # dir: ./outputs_hydra/${hydra.job.config_name}_${global_device}

output_path: ${hydra:runtime.output_dir}
global_device: "cuda"

dataset_config:
  dataset_type: "measured-setpoint" # either "measured-setpoint" or "actual-measured"
  include_prev_measured: true

train_config:
  batch_size: 32
  epochs: 150
  lr: 0.0008
  log_interval: 1

actions:
  train: true
  test: true

test_config:
  batch_size: 32
